### PR TITLE
prepare 0.4.2

### PR DESCRIPTION
**Pull request by Nazariglez**
It would be great to publish a new version after all PRs get merged. Thanks!

- - -
This change is [Reviewable](https://reviewable.io/reviews/rustgd/glsl-layout/17)

### CODE REVIEW

**Comment by zakarumych** [comment]
Would be cool to keep a changelog.
You can add one and write what changed between 0.4.1 and 0.4.2
If you do, use https://keepachangelog.com/en/1.0.0/ as a template

**Comment by Nazariglez** [comment]
Done! I added the date for release as tomorrow, but feel free of change it, I am not sure when you're going to release it. 

Thanks!

**Comment by zakarumych** [comment]
When? A minute ago!

**Comment by Nazariglez** [comment]
hahaha thanks!

**Pull request merged**
